### ISSUE TITLE
Need help integrating

### ISSUE THREAD

**Issue by laurentyew** [MOLPay/Mobile_SDK-Android#10]
i have tested the integration , i manage to make payment via credit card and while waiting for the response , i got this error shown

10-06 21:20:28.147: W/cr.BindingManager(11826): Cannot call determinedVisibility() - never saw a connection for the pid: 11826
10-06 21:20:29.926: W/cr.BindingManager(11826): Cannot call determinedVisibility() - never saw a connection for the pid: 11826
10-06 21:20:41.174: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string
10-06 21:20:41.381: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string
10-06 21:20:43.538: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string
10-06 21:20:44.421: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string
10-06 21:20:44.660: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string
10-06 21:20:46.555: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string
10-06 21:20:46.938: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string
10-06 21:20:47.242: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string
10-06 21:20:51.894: W/cr.BindingManager(11826): Cannot call determinedVisibility() - never saw a connection for the pid: 11826
10-06 21:21:04.155: W/cr.BindingManager(11826): Cannot call determinedVisibility() - never saw a connection for the pid: 11826
10-06 21:21:04.701: W/cr.BindingManager(11826): Cannot call determinedVisibility() - never saw a connection for the pid: 11826
10-06 21:21:04.784: W/cr.BindingManager(11826): Cannot call determinedVisibility() - never saw a connection for the pid: 11826

and the public void onActivityResult  function was not called. please advice

**Comment by tekjau** [comment]
will look into it

**Comment by MedetZhakupov** [comment]
May I know what version of the Android you were running on when it's happened

**Comment by laurentyew** [comment]
Android 5.1.1 . was using a previous version of sdk. Just noticed that you release a new one 5 days ago. but i think it shouldn't matter right?

**Comment by MedetZhakupov** [comment]
Because I found in google's bug track there is this kind a problem since version 5.0 of Android, but, anyway there are another few possible reasons for that and I've fixed them. So please download new version and try it out.

**Comment by laurentyew** [comment]
i have tested to integrate the latest build. and notice it runs fine on the 4.4.1 but on 5.1.1 , i get error whereby when i start to intitiate payment by calling the molpay activity , all is shown is a blank page with molpay logo on the top left side

**Comment by tekjau** [comment]
Do you have all the required credentials? such as api_username/password and have you registered your app name with MOLPay support team?

**Comment by laurentyew** [comment]
yes i did. as mentioned. it was running fine on 4.4.1 with successful payment.

**Comment by laurentyew** [comment]
Testing on 4.4.2 , it worked with successful payment . bu the onActivityResult was not triggered. please advice

**Comment by laurentyew** [comment]
Any thoughts?

**Comment by zabogarz** [comment]
is there any Empty Key Map Entries?

see https://chromium.googlesource.com/chromium/src/+/4675e7cbedf99fcc18ae9bfcf19225740fed9387/ui/events/keycodes/dom4/keycode_converter.cc

on line 84-93 said 
DomCode KeycodeConverter::NativeKeycodeToDomCode(int native_keycode) {
  for (size_t i = 0; i < kKeycodeMapEntries; ++i) {
    if (usb_keycode_map[i].native_keycode == native_keycode) {
      if (usb_keycode_map[i].code != NULL)
        return static_cast<DomCode>(usb_keycode_map[i].usb_keycode);
      break;
    }
  }
  return DomCode::NONE;
}

**Comment by laurentyew** [comment]
Sorry, couldn't understand what you mean? please elaborate

**Comment by zabogarz** [comment]
is error occured when you type something in keyboard? or when keyboard shown?? 
its chrome 44 issue..  

10-06 21:20:47.242: W/chromium(11826): [WARNING:keycode_converter.cc(91)] empty code string <== its chrome issue try ignore this like chrom does
ref: https://github.com/atom/electron/issues/2973

Cannot call determinedVisibility() - never saw a connection for the pid: 11826 <== please try this webView.getSettings().setDomStorageEnabled(true);
ref: http://stackoverflow.com/questions/29592695/android-webview-wont-load-my-url-but-will-load-others

**Comment by laurentyew** [comment]
the error did not occur when i type something i keyboard nor keyboard showing. i was inititating via calling of the method in jar library. not a webview thus how could i set webView.getSettings().setDomStorageEnabled(true);

**Comment by medetsiswa** [comment]
Have you guys tried new version? I've released version 5.0.4 and there I put
webView.getSettings().setDomStorageEnabled(true);. So please try it one more time.

**Comment by MedetZhakupov** [comment]
Have you guys tried new version? I've released version 5.0.4 and there I put
webView.getSettings().setDomStorageEnabled(true);. So please try it one more time.

**Comment by laurentyew** [comment]
i tried to download the files. don't see anything in github

**Comment by laurentyew** [comment]
checked the history. it is missing the MOLPay SDK/molpaysdk jar

**Comment by MedetZhakupov** [comment]
Could you try it now. Due to network issue it's uploaded just now.

**Comment by laurentyew** [comment]
still not working for both issues.  onactivityresult is not called for 4.4.2  , molpay screen blank for 5.1.1

**Comment by laurentyew** [comment]
i'm doing this

 Intent intent = new Intent(getActivity(), MOLPayActivity.class);
         intent.putExtra(PConstants.MP_MERCHANT_ID, ""); <--- removed for posting purpose
         intent.putExtra(PConstants.MP_APP_NAME, ""); <--- removed for posting purpose
         intent.putExtra(PConstants.MP_VERIFICATION_KEY, "a10019784b78189ffe0ae69c3af4aecc");
         intent.putExtra(PConstants.MP_USERNAME, "");  <--- removed for posting purpose
         intent.putExtra(PConstants.MP_PASSWORD, ""); <--- removed for posting purpose
         intent.putExtra(PConstants.MP_ORDER_ID, "DEMO123");
         intent.putExtra(PConstants.MP_COUNTRY, "MY");
         intent.putExtra(PConstants.MP_AMOUNT, "1.10");
         intent.putExtra(PConstants.MP_BILL_NAME, "MOLPay DEMO");
         intent.putExtra(PConstants.MP_BILL_EMAIL, "demo@mail.com");
         intent.putExtra(PConstants.MP_BILL_MOBILE, "01123232323");
         intent.putExtra(PConstants.MP_BILL_DESCRIPTION, "Purchase of 5 units");
         intent.putExtra(PConstants.MP_CURRENCY, "MYR");
         intent.putExtra(PConstants.MP_CHANNEL, "multi");

         intent.putExtra(PConstants.MP_EDITING_ENABLED, true);
         intent.putExtra(PConstants.MP_RECEIPT_ENABLED, true);
         intent.putExtra(PConstants.MP_SECURE_MODE_ENABLED, false);
         intent.putExtra(PConstants.MP_IS_ESCROW, false);
         intent.putExtra(PConstants.MP_ACTION_BAR_COLOR, getActivity().getResources().getColor(R.color.lightRed));
         ((MainAcitvityForCustomNavigator)getActivity()).startActivityForResult(intent, 10001);



public void onActivityResult(int requestCode, int resultCode, Intent data) {
		super.onActivityResult(requestCode, resultCode, data);
		 if (requestCode == 10001 && resultCode == getActivity().RESULT_OK){
	            try{
	                String status = data.getStringExtra(PConstants.MP_STATUS_CODE).equals("00") ?
	                        "Successful" : data.getStringExtra(PConstants.MP_STATUS_CODE).equals("11") ?
	                        "Failed" : "Pending";

	                
	                Log.e("","status= "+status+" transtaion id= "+data.getStringExtra(PConstants.MP_TRANSACTION_ID));
	            }catch (Exception e){
//	                e.printStackTrace();
	            }
	        }


it doesn't even get to super.onActivityResult(requestCode, resultCode, data);   when i debug it

**Comment by laurentyew** [comment]
wondering have it bee successful for you guys on 4.4.2 as well?

**Comment by zabogarz** [comment]
((MainAcitvityForCustomNavigator)getActivity()).startActivityForResult(intent, 10001); 
would you try  change the line to 
startActivityForResult(intent, 10001);

**Comment by laurentyew** [comment]
Thanks! that does it. the 5.1.1 blank page issue is not solved

**Comment by zabogarz** [comment]
hi MedetZhakupov.. since we cant touch the webview, would you try set the getter the webView for us ??

**Comment by MedetZhakupov** [comment]
I am wandering how is yours is blank. I've tested on 4.4.2 MI Phone and 5.1.1 nexus 5 and 6.0 nexus 5. 
Eventually, all og them works fine. Could you say it's happening in all channels or specific one. Moreover, Have you tried to run example project itself?

**Comment by laurentyew** [comment]
![screenshot_2015-10-16-15-29-51](https://cloud.githubusercontent.com/assets/5634301/10536097/f71c876c-741a-11e5-97f0-9a024690438d.png)

ok. hmm.. definately my problem then.... screenshot of what was on my hone

**Comment by MedetZhakupov** [comment]
So could you try example app first. What does it show?

**Comment by laurentyew** [comment]
don't have an eclipse with me now. doing it later the day

**Comment by mqadhavi** [comment]
do you use jQuery mobile? I think its compatibility issue for jQuery mobile and android 5.0 above, 
http://stackoverflow.com/questions/30875099/cannot-call-determinedvisibility-never-saw-a-connection-for-pid

**Comment by MedetZhakupov** [comment]
We don't use any JQuery. Could you pass all your data which you are passing to SDK and an what device it's happening to our support. So we could troubleshot our case.

**Comment by laurentyew** [comment]
Hi sorry , did not notice the last comment.  one of my client tested with the same issue as well , using Samsung j2 phone with android 5.1.1

**Comment by laurentyew** [comment]
i will try to use the demo app again later

**Comment by mqadhavi** [comment]
Sorry sir, I did not noticed the comment, its was going to my spam, I will
checked tonight.

**Comment by laurentyew** [comment]
i have tested out using the example and it works. i'm not sure what is going on with the integration with my app.  1 possibility is i use the universal image loader  as well , not sure is that clashing with your jar. possible to create a jar without the universal image loader classes?

**Comment by MedetZhakupov** [comment]
May I know the exactly the problem? Do you use OkHttp in your project as well?

**Comment by laurentyew** [comment]
Hi,

i do not use OKHttp. just normal http . just the usual HttpClient  standard stuffs . 

i tried to use the example codes in my project. and it did not show. Means some library or project is clashing.  i'm using eclipse instead of android studio at the moment
library that i used include

facebook
universalimageloader
MFCalendarView

i don't think android support library would have an impact on this. right?

**Comment by laurentyew** [comment]
we could discuss further on skype : laurentyew

**Comment by MedetZhakupov** [comment]
Then I suggest you just remove the universalimageloader from your project. And use one inside our SDK(package name will be the same so it won't affect your code) and you just initalize universalimageloader in your Application class as usual. Should be fine.

**Comment by laurentyew** [comment]
tried that as well. as it would cause an compilation error . so i have removed it from my build path. still issue remain

**Comment by laurentyew** [comment]
after stripping down the example  project  , i have now found the cause , although not 100% there

1) including the appcompat v7 support library is a must as the following line will error out in sdk. (advice to use the lastest version possible)

2)  in the styles.xml  , the following line is a must to make style as Theme.AppCompat.Light.DarkActionBar . so far others seems to not work for me

  <style name="AppBaseTheme" parent="Theme.AppCompat.Light.DarkActionBar">
      
    </style>

so these are my findings ....

**Comment by MedetZhakupov** [comment]
Ok. Noted. I will try to reproduce your error to fix it if there is problem

**Comment by nguyenvoc** [comment]
Hey laurent, is your problem solved? I'm facing the same "blank page" problem. Would you mind to share you solution here?

**Comment by laurentyew** [comment]
yes . i assume , it blank page on 5.1.1  .  you will need to make sure your support library v7 is the latest.  the style.xml need to have the line parent="Theme.AppCompat.Light.DarkActionBar"   for the appbasetheme 

and also the androidmanifest.xml  app theme set to the appbasetheme

**Comment by nguyenvoc** [comment]
mine is 5.0.1 with v7:22.2.1, v7 has to be the latest? 

the appbasetheme part I do not think I understand you. So sorry. mind explain ?

**Comment by clewlb** [comment]
Please upgrade to our latest Android SDK at https://github.com/MOLPay/molpay-mobile-xdk-android
